#!/bin/bash
main() {
  local container_id="$1"; shift
  local port="$1"; shift
  local ext_ports=$(docker inspect -f '{{range $i,$e := .NetworkSettings.Ports}}{{ $i }} {{$p := index $e 0}}{{$p.HostPort}}\n{{end}}' $container_id)
  local ext_port=$(echo -e "${ext_ports}"|awk "/${port}/{print \$2}")
  local path="$1"; shift
  local opts="$@"
  local ip=${MASTER_IP}
  curl \
    --silent \
    --show-error \
    --fail \
    --dump-header /dev/stderr \
    --retry 2 \
    $opts \
    http://${ip}:${ext_port}${path} > /dev/null
}
main $@
