#!/bin/bash
# Dummy docker wrapper to provide CONTAINER_NAME
# inside mesos containers

DOCKER=/usr/bin/docker

[ "$1" = "run" ] && {
  shift
  CONTAINER_NAME=$(echo "$@" | sed -n 's/.*--name \(mesos[-0-9A-z\.]*\).*/\1/p') 
  MESOS_CONTAINER_NAME=${CONTAINER_NAME}
  $DOCKER run -e CONTAINER_NAME=${CONTAINER_NAME} -e MESOS_CONTAINER_NAME=${MESOS_CONTAINER_NAME} "$@"
} || {
  $DOCKER "$@"
}
exit $?
